### ISSUE TITLE
Cleanup & refactor

### ISSUE THREAD

**Issue by mpp-admin** [multiplayerpiano/mpp-frontend-v1#2]
Tasks:

 - Setup webpack & typescript and make it runnable
 - Convert to typescript 
 - split into files
 - es6 import syntax
 - es6 class syntax (no more prototype)
 - remove global references

Please make pr as you go and I'll review

**Comment by BopItFreak** [comment]
One reason why Brandon never converted the files to es6 syntax (classes, no more of that mixin function garbage), was to make sure old browsers could connect to the site. I think he used to check google analytics all the time.

**Comment by mpp-admin** [comment]
Doesn't matter, because we will compile to es5. I need to setup webpack and babel.

Nobody running real apps should deliver raw source code like this... Very hard to maintain

**Comment by Hri7566** [comment]
Marked in done because of new typescript repo, but keeping this issue open for further discussion

**Comment by Hri7566** [comment]
One week has passed with no word on the project.
